## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/appcast.xml"
  to = "https://update.selfcontrolapp.com/feeds/selfcontrol"
  status = 301 
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/support"
  to = "https://github.com/SelfControlApp/selfcontrol/wiki/SelfControl-Support-Hub"
  status = 301
  force = true # COMMENT: ensure that we always redirect
